achievements:
  kafka:
    topic: ${TOPIC_NAME}

spring:
  application:
    name: achievement-service

  datasource:
    url: jdbc:${DB_ENGINE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: ${JPA_SHOW_SQL:false}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
